default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: twork_development

test:
  <<: *default
  database: twork_test

production:
  <<: *default
  database: <%= ENV['TWORK_DATABASE'] %>
  username: <%= ENV['TWORK_DATABASE_USERNAME'] %>
  password: <%= ENV['TWORK_DATABASE_PASSWORD'] %>
  host: <%= ENV['TWORK_DATABASE_HOSTNAME'] %>
  port: <%= ENV['TWORK_DATABASE_PORT'] %>